language: node_js
node_js:
- '8.9'
- node
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run lint
- npm run test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: KzU3IdnV+58UXbvVzdehPUtO4IL0/A0Bl13zxHU0Ev/wtJFmnHZeSbtTdMtZYaWmqTYbtAeoH6lOXHjNsSE41p7OU2x7NZV/+VXNpGSLzG51ktOvcxgUo8IsmVmm4wyC88hf5e0uEVtZOPUUOKcOhEFBS87WTLe/kULlQsOxSJX18CxzMtGKPMEpKU3weacDgFOf7OhP4u+wdkHoZh+vpS4VXEg9loZPH/WkingcEQiizgWeWDzWs0hCyUC1A5pC8MUkmDyDLA84M71tSBT6snzG1df3Ep8HkRHBA7X/ipRAuL6ch3tJAKRV390//uCHOIpWZaj0lTRB8em8oVD+ddX2QcoFK+3pnfONzJR8ibKXFuflyXIU3zU8fcrsJqwUzNA+QPF/B1dh72J0T7cxt9j0F0kPadAacDvwevxyImsuDVR3uEUm42nV7aBPvUEnEhuUnnj8JUCFArCoDBPxttDQJlamq6VQ8Mphz4fG9L2E4oKVJ0c5iRGypuehnPz8WbzVSefXem94vzykgHYaNLLSDVEicZouaRkTfh0SL5fhvzB9TAW2Fe4CvW5xH/mrJOmNZSXf4lTSf8k2Mn+Z7aE5u2Ttckp7GXoza34HoGqDBqhWn7Edtv80FnKCAC6Mq5bQJUelWnx8FhZxW3xrm+yx1BG66Vq3fYVwleOIXdU=
