version: '3'
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisVolume:/bitnami/redis/data
volumes:
  redisVolume:
